### ISSUE TITLE
Incorrect test for time

### ISSUE THREAD

**Issue by ImmortalTurtle** [AntonKozlov/eduos#28]
I did some tests and it seems that [test for time](https://github.com/AntonKozlov/eduos/blob/master/test/t/time/run.sh#L8) doesn't work properly. 
It's possible that I don't understand some of that, but it still doesn't work :p

**Comment by AntonKozlov** [comment]
The `time` test checks for 2 facts:
1. uptime "works", i.e. it senses time flow during execution
2. sleep sleeps for a specified amount of time; respecting to uptime measurement

Actually there was no strict requirements time inside eduos be the same as real-world time. The #29 is better in one side: eduos sleep should sleep for specified amount of real-world seconds; but it skips checking uptime: uptime reporting `0` seems to pass the test

But that is a good idea, I combined old test with your suggested changes in https://github.com/AntonKozlov/eduos/commit/e7e47058fc10ac80282aeb07e9414f4bd296b924
Tested on these simple implementation https://github.com/AntonKozlov/eduos/commit/b793163ef0ed143fb094ff66b528b1135b91df1c

Please review mentioned commits and respond if you're ok with them

**Comment by ImmortalTurtle** [comment]
Yes, these commits seem to solve the problem. And now it's also clear how is `uptime` supposed to work. Thank you.

**Comment by AntonKozlov** [comment]
1.sh is just testing scenario for test function itself.

Thanks, I'm going to merge `fix-28` branch to master. What is preferable, to include `uptime` and `sleep` sample implementation or skip that?

**Comment by ImmortalTurtle** [comment]
@AntonKozlov I think, it is better to include these, but put "TODO" in both of these functions (it might not be clear how to solve FIXME - delete `#include <stdlib.h>`) to highlight that there are supposed to be our system functions. 
And also in `uptime` mention that it's supposed to print time since launch of the kernel (unlike existing `date +%s.%N`).

**Comment by AntonKozlov** [comment]
OK, pushed, thanks
